### ISSUE TITLE
Validate exclusion of reserved words for application_name

### ISSUE THREAD

**Issue by rafaltrojanowski** [pdabrowski6/buildless#1]
```
buildless apply 6afe770a-86ef-400a-bb40-63c7d2dd90e6

true
true
Based on the specified options, the following options will also be activated:

  --skip-hotwire [due to --skip-javascript]

Invalid application name test. Please give a name which does not match one of the reserved rails words: application, destroy, plugin, runner, test
/Users/rafaltrojanowski/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/buildless-app-0.0.7/lib/buildless-app.rb:44:in `chdir': No such file or directory @ chdir_path - test (Errno::ENOENT)
```

Maybe I could help with this issue? I just need a guidance on where to put `validates_exclusion_of` method?

**Comment by pdabrowski6** [comment]
Hey @rafaltrojanowski 👋 it should be placed on the backend, but it's not currently open-sourced. The gem is quite simple and it's only responsible for taking the instructions and executing simple commands. I appreciate your willingness to help but I will have to do this on my own. Thank you for pointing this out, it's really important to have this validation in place.
